[workspace]
resolver = "2"

members = [
    "common",
    "server"
]

[workspace.dependencies]
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
itertools = "0.12.1"

[profile.release]
lto = true
codegen-units = 1
strip = true