[package]
name = "server"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
rusqlite = { version = "0.31.0", features = ["bundled"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
